export const GET_LEADS="GET_LEADS";
export const DELETE_LEADS="DELETE_LEADS";
export const ADD_LEADS="ADD_LEADS";
export const ADD_ERROR="ADD_ERROR";

 // Login module action types

export const ALERT_CREATE_USER="ALERT_CREATE_USER";
export const ALERT_GET_USER="ALERT_GET_USER";
export const LOGIN_USER_LOADING="USER_LOADING";
export const LOGIN_USER_LOADED="USER_LOADED";
export const LOGIN_AUTH_ERROR="LOGIN_AUTH_ERROR";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";
export const CONFIRM_USER_SUCCESS="CONFIRM_USER_SUCCESS";
export const CONFIRM_USER_FAIL="CONFIRM_USER_FAIL";
export const CONFIRM_PHONE_SUCCESS="CONFIRM_PHONE_SUCCESS";
export const CONFIRM_PHONE_FAIL="CONFIRM_PHONE_FAIL";
export const CONFIRM_LEGAL_SUCCESS="CONFIRM_LEGAL_SUCCESS";
export const CONFIRM_LEGAL_FAIL="CONFIRM_LEGAL_FAIL";
export const GET_CURRENT_DATE_TIME_SUCCESS="GET_CURRENT_DATE_TIME_SUCCESS";
export const GET_CURRENT_DATE_TIME_FAIL="GET_CURRENT_DATE_TIME_FAIL";
export const GET_UPDATED_USER_SUCCESS = "GET_UPDATED_USER_SUCCESS";
export const GET_UPDATED_USER_FAIL = "GET_UPDATED_USER_FAIL";
export const UPDATE_USER_PROFILE_SUCCESS="UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL="UPDATE_USER_PROFILE_FAIL";

 // Joins module action types

export const LOAD_PERIODS_DATA_SUCCESS="LOAD_PERIODS_DATA_SUCCESS";
export const LOAD_PERIODS_DATA_FAIL="LOAD_PERIODS_DATA_FAIL";
export const LOAD_MONTH_DURATIONS_DATA_SUCCESS="LOAD_MONTH_DURATIONS_DATA_SUCCESS";
export const LOAD_MONTH_DURATIONS_DATA_FAIL="LOAD_MONTH_DURATIONS_DATA_FAIL";
export const LOAD_AMOUNTS_DATA_SUCCESS="LOAD_AMOUNTS_DATA_SUCCESS";
export const LOAD_AMOUNTS_DATA_FAIL="LOAD_AMOUNTS_DATA_FAIL";
export const LOAD_CATEGORY_DATA_SUCCESS="LOAD_CATEGORY_DATA_SUCCESS";
export const LOAD_CATEGORY_DATA_FAIL="LOAD_CATEGORY_DATA_FAIL";
export const CREATE_STATUS_SUCCESS="CREATE_STATUS_SUCCESS";
export const CREATE_STATUS_FAIL="CREATE_STATUS_FAIL";
export const CREATE_FIRST_PAYMENT_SUCCESS="CREATE_FIRST_PAYMENT_SUCCESS";
export const CREATE_FIRST_PAYMENT_FAIL="CREATE_FIRST_PAYMENT_FAIL";
export const GET_GROUP_DATA_SUCCESS="GET_GROUP_DATA_SUCCESS";
export const GET_GROUP_DATA_FAIL="GET_GROUP_DATA_FAIL";
export const SET_GROUP_NAME_SUCCESS="SET_GROUP_NAME_SUCCESS";
export const SET_GROUP_NAME_FAIL="SET_GROUP_NAME_FAIL";
export const GET_GROUP_MEMBERS_SUCCESS="GET_GROUP_MEMBERS_SUCCESS";
export const GET_GROUP_MEMBERS_FAIL="GET_GROUP_MEMBERS_FAIL";
export const GET_WINNERS_SUCCESS="GET_WINNERS_SUCCESS";
export const GET_WINNERS_FAIL="GET_WINNERS_FAIL";

export const FIRST_ONLINE_PAY_SUCCESS="FIRST_ONLINE_PAY_SUCCESS";
export const FIRST_ONLINE_PAY_FAIL="FIRST_ONLINE_PAY_FAIL";
export const FIRST_ONLINE_CHARGE_SUCCESS="FIRST_ONLINE_CHARGE_SUCCESS";
export const FIRST_ONLINE_CHARGE_FAIL="FIRST_ONLINE_CHARGE_FAIL";
export const SET_ONLINE_AMOUNT_SUCCESS="SET_ONLINE_AMOUNT_SUCCESS";
export const JOIN_STATE_RESET_SUCCESS = "JOIN_STATE_RESET_SUCCESS";

 // Status module action types

export const STATUS_GET_GROUP_MEMBERS_SUCCESS="STATUS_GET_GROUP_MEMBERS_SUCCESS";
export const STATUS_GET_GROUP_MEMBERS_FAIL="STATUS_GET_GROUP_MEMBERS_FAIL";
export const STATUS_GET_WINNERS_SUCCESS="STATUS_GET_WINNERS_SUCCESS";
export const STATUS_GET_WINNERS_FAIL="STATUS_GET_WINNERS_FAIL";
export const STATUS_SET_GROUP_CAT_ID_SUCCESS="STATUS_SET_GROUP_CAT_ID_SUCCESS";
export const STATUS_SET_GROUP_CAT_ID_FAIL="STATUS_SET_GROUP_CAT_ID_FAIL";
export const STATUS_RESET_STATE_SUCCESS = "STATUS_RESET_STATE_SUCCESS";
export const STATUS_GET_SALE_LOT_SUCCESS="STATUS_GET_SALE_LOT_SUCCESS";
export const STATUS_GET_SALE_LOT_FAIL = "STATUS_GET_SALE_LOT_FAIL";
export const STATUS_GIVE_FEEDBACK_SUCCESS="STATUS_GIVE_FEEDBACK_SUCCESS";
export const STATUS_GIVE_FEEDBACK_FAIL = "STATUS_GIVE_FEEDBACK_FAIL";
export const STATUS_CHECK_BALANCE_SUCCESS="STATUS_CHECK_BALANCE_SUCCESS";
export const STATUS_CHECK_BALANCE_FAIL = "STATUS_CHECK_BALANCE_FAIL";

// Pay_manual module action types

export const MANUAL_PAY_SUCCESS="MANUAL_PAY_SUCCESS";
export const MANUAL_PAY_FAIL="MANUAL_PAY_FAIL";

// Pay_online module action types

export const ONLINE_PAY_SUCCESS="ONLINE_PAY_SUCCESS";
export const ONLINE_PAY_FAIL="ONLINE_PAY_FAIL";
export const ONLINE_CHARGE_SUCCESS="ONLINE_CHARGE_SUCCESS";
export const ONLINE_CHARGE_FAIL="ONLINE_CHARGE_FAIL";
export const GET_SELECTED_AMOUNT_SUCCESS="GET_SELECTED_AMOUNT_SUCCESS";
export const GET_SELECTED_AMOUNT_FAILL="GET_SELECTED_AMOUNT_FAIL";
export const PAY_STATE_RESET_ACTION = "PAY_STATE_RESET_ACTION";


// admin module action
export const ADMIN_ADD_USER_SUCCESS="ADMIN_ADD_USER_SUCCESS";
export const ADMIN_ADD_USER_FAIL="ADMIN_ADD_USER_FAIL";
export const ADMIN_GET_FEEDBACK_SUCCESS="ADMIN_GET_FEEDBACK_SUCCESS";
export const ADMIN_GET_FEEDBACK_FAIL="ADMIN_GET_FEEDBACK_FAIL";
export const ADMIN_GET_GROUPS_SUCCESS="ADMIN_GET_GROUPS_SUCCESS";
export const ADMIN_GET_GROUPS_FAIL="ADMIN_GET_GROUPS_FAIL";
export const ADMIN_GET_WINNERS_SUCCESS="ADMIN_GET_WINNERS_SUCCESS";
export const ADMIN_GET_WINNERS_FAIL="ADMIN_GET_WINNERS_FAIL";
export const ADMIN_DELETE_GROUP_SUCCESS="ADMIN_DELETE_GROUP_SUCCESS";
export const ADMIN_DELETE_GROUP_FAIL="ADMIN_DELETE_GROUP_FAIL";
export const ADMIN_ADD_PERIOD_SUCCESS="ADMIN_ADD_PERIOD_SUCCESS";
export const ADMIN_ADD_PERIOD_FAIL="ADMIN_ADD_PERIOD_FAIL";
export const ADMIN_ADD_DURATION_SUCCESS="ADMIN_ADD_DURATION_SUCCESS";
export const ADMIN_ADD_DURATION_FAIL="ADMIN_ADD_DURATION_FAIL";
export const ADMIN_ADD_AMOUNT_SUCCESS="ADMIN_ADD_AMOUNT_SUCCESS";
export const ADMIN_ADD_AMOUNT_FAIL="ADMIN_ADD_AMOUNT_FAIL";
export const ADMIN_ADD_CATEGORY_SUCCESS="ADMIN_ADD_CATEGORY_SUCCESS";
export const ADMIN_ADD_CATEGORY_FAIL="ADMIN_ADD_CATEGORY_FAIL";
export const ADMIN_GET_ACTIVITIES_SUCCESS="ADMIN_GET_ACTIVITIES_SUCCESS";
export const ADMIN_GET_ACTIVITIES_FAIL="ADMIN_GET_ACTIVITIES_FAIL";
export const ADMIN_GET_USER_SUCCESS="ADMIN_GET_USER_SUCCESS";
export const ADMIN_GET_USER_FAIL="ADMIN_GET_USER_FAIL";
export const ADMIN_DELETE_USER_SUCCESS="ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_FAIL="ADMIN_DELETE_USER_FAIL";
export const ADMIN_GET_BALANCE_SUCCESS="ADMIN_GET_BALANCE_SUCCESS";
export const ADMIN_GET_BALANCE_FAIL="ADMIN_GET_BALANCE_FAIL";
export const ADMIN_GET_PERIODS_SUCCESS="ADMIN_GET_PERIODS_SUCCESS";
export const ADMIN_GET_PERIODS_FAIL="ADMIN_GET_PERIODS_FAIL";
export const ADMIN_GET_DURATIONS_SUCCESS="ADMIN_GET_DURATIONS_SUCCESS";
export const ADMIN_GET_DURATIONS_FAIL="ADMIN_GET_DURATIONS_FAIL";
export const ADMIN_GET_AMOUNTS_SUCCESS="ADMIN_GET_AMOUNTS_SUCCESS";
export const ADMIN_GET_AMOUNTS_FAIL="ADMIN_GET_AMOUNTS_FAIL";
export const ADMIN_GET_CATEGORY_SUCCESS="ADMIN_GET_CATEGORY_SUCCESS";
export const ADMIN_GET_CATEGORY_FAIL="ADMIN_GET_CATEGORY_FAIL";
export const ADMIN_RESET_STATE_SUCCESS="ADMIN_RESET_STATE_SUCCESS";

// sale buy
export const SALE_BUY_SELL_SUCCESS="SALE_BUY_SELL_SUCCESS";
export const SALE_BUY_SELL_FAIL="SALE_BUY_SELL_FAIL";
export const SALE_SET_GROUP_CAT_ID_SUCCESS="SALE_SET_GROUP_ID_SUCCESS";
export const SALE_SET_GROUP_CAT_ID_FAIL="SALE_SET_GROUP_ID_FAIL";
export const SALE_BUY_BUY_SUCCESS="SALE_BUY_BUY_SUCCESS";
export const SALE_BUY_BUY_FAIL="SALE_BUY_BUY_FAIL";
export const SALE_BUY_SET_ID_SUCCESS = "SALE_BUY_SET_ID_SUCCESS";
export const SALE_BUY_SET_ID_FAIL = "SALE_BUY_SET_ID_FAIL";
export const SALE_BUY_GET_PREPAYMENT_SUCCESS = "SALE_BUY_GET_PREPAYMENT_SUCCESS";
export const SALE_BUY_GET_PREPAYMENT_FAIL = "SALE_BUY_GET_PREPAYMENT_FAIL";
export const SALE_BUY_Buy_PayManual_SUCCESS = "SALE_BUY_Buy_PayManual_SUCCESS";
export const SALE_BUY_Buy_PayManual_FAIL = "SALE_BUY_Buy_PayManual_FAIL";
export const SALE_BUY_ONLINE_PAY_SUCCESS="SALE_BUY_ONLINE_PAY_SUCCESS";
export const SALE_BUY_ONLINE_PAY_FAIL="SALE_BUY_ONLINE_PAY_FAIL";
export const SALE_BUY_ONLINE_CHARGE_SUCCESS="SALE_BUY_ONLINE_CHARGE_SUCCESS";
export const SALE_BUY_ONLINE_CHARGE_FAIL="SALE_BUY_ONLINE_CHARGE_FAIL";
export const SALE_BUY_STATE_RESET_SUCCESS="SALE_BUY_STATE_RESET_SUCCESS";